language: python
cache:
  directories:
  - "$HOME/.cache/pip"
os:
- linux
before_install:
- pip install cython numpy biopython
install:
- pip install .
script:
- pytest -s -v --color=yes test/
deploy:
  - provider: pypi
    username: "__token__"
    password:
      secure: "OI+Cx22V+036b1TWWCD8NoVO3SLDxmRH1ar8MZWWP1Ar2hEkPQZiXquVpRBm2u/pCmLXiL1EH8mt/uLyxcUYG6d5h9X3hXPRRSU/KGnLc277A1eBRQZ5C5Req1JlCk4SWQiJ/NM0yMRGjUsTkwvmIHGqHl+mm9RJG/hKVbHKTf5cBMY49aIJumvtybgjhTnfDoKY2H0Oe+4l4M+X5ilMVHJLnYKwhaMMQD+KtIOCV5p6AWwbtZglmpiSbG9g062v53/RoKXUG6BOD7bH3V5U6I4fXIdnK495d2ucRj+V7vbdh+fyXhjsxWQ4F5UlZeM9tDhWKpxFLGRwqm6vO1dxcEGIrBNdYy6Z+qWsFCeHossw/a70HgnLrWZSJ5CETZa44Vi7XIFJtM1pJYJRAewUIPuWe9yWlgukSlqYoMNmMtdMNQ2tY+NEDiiHQ0DvqALYkh3eqMFiSPtPOyBCoeiDp3f4LLbWKKw/Wrln2/u0p2MhYXKLsWjAB1ggZ+CGz1l9TsvELMJ0HRWFuWvvfqYF56SqOMbyFBSlGiZgR15HbeuPiaf/IwotyqHWg3sQXBE9KTRgBfC23/4Tt15rcjWguEIsKU1CMnjG3r5EG6uO2w9Zcwgs4GrfO03VRhTti8ZDKQCdHz1uQAkYRW1H9XFqpJLEeGmlHpVqH2xGGpon2w0="
    on:
      tags: true
    distributions: "sdist"
  - provider: pypi
    server: https://test.pypi.org/legacy/
    username: "__token__"
    password:
      secure: "lyypaqkNdAS6gWRVkxvRgbq4vcAvOMdbBh7PUhrjXBTIb3ZLNS6KkotBLk+l5ZpENL24QnCjDsIoKsMEO0qQ4e2tQwsrQPTHI+54/vFow2GfLT2pvULv/z37hX2wgpq7zEzzCNeD6Esuicvn3Y8x+2P6/+8zogMctQKGtbtN+JSfPw6GEYWY63M2fUREN5O0gQzmZcdQ6GKkG4KGii/fouZVAG2p9yvhm997saOOD0hVeGxRqLumGYDkGNZp0OOkPShcsWqIDOeSTjCsr3Ucp0zEKWh+27hPzoVaV073OigGaqWVagEatujHahHZQQBJG1IQIPKPBevHC1pch+zF/RgaOcYi8U1BaqOTMJvGD+gdQyFrrUyW5YcJdZoAy07Fqb0cj94gXSls7EYg5SWmyAxzLnpogftGX2BI1HBVAHWDLCQouRfX8mNdpICuF1GD55MuCYZLsGshDEZsU7T6X+5bZAfVeIZ+sqGbAZgx0DqYuI9syBU5jZ28k/I1lhcA71q47Eh+zQn4SdkouYcpSrlt6XCDIvHWVP49wkYJtThHiKwx4MXYh2p5Y4el4Qcc95EltXStqoLnaFQpwSbHiX5qHQolJuNWxTuXGSntqeyc5odfZYr7pF1BRKKjBgwF5O8z8Mmx85pE0JN7fydwpkF7nz4cCjYKVGwSGnQUdJs="    on:
    distributions: "sdist"
